config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foodlogs do
  	resources :details
  end
  root 'foodlogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :foodlog
end

app/models/foodlog.rb
class Foodlog < ApplicationRecord
	belongs_to :user
	has_many :details, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :foodlogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
	def create
		@foodlog = Foodlog.find(params[:foodlog_id])
		@detail = @foodlog.details.create(params[:detail].permit(:calories, :carbohydrates, :levels, :extra))

		redirect_to foodlog_path(@foodlog)
	end

end

app/controllers/foodlogs_controller.rb
class FoodlogsController < ApplicationController
	before_action :find_foodlog, only: [:show, :edit, :update, :destroy]

	def index
		@foodlogs = Foodlog.all.order("created_at DESC")
	end

	def show

	end

	def new
		@foodlog = current_user.foodlogs.build
	end

	def create
		@foodlog = current_user.foodlogs.build(foodlog_params)
		if @foodlog.save
			redirect_to @foodlog
		else
			render'new'
		end
	end

	def edit
	end

	def update
		if @foodlog.update(foodlog_params)
			redirect_to @foodlog
		else
			render 'edit'
		end
	end

	def destroy
		@foodlog.destroy
		redirect_to root_path
	end

	private 

	def foodlog_params
		params.require(:foodlog).permit(:date, :mealtype, :meal, :mood, :level)
	end

	def find_foodlog
		@foodlog = Foodlog.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/foodlogs_helper.rb
module FoodlogsHelper
end

app/views/details/_detail.html.haml
%p= detail.calories
%p= detail.carbohydrates
%p= detail.levels
%p= detail.extra

app/views/details/_form.html.haml
= simple_form_for([@foodlog, @foodlog.details.build]) do |f|
	= f.input :calories, input_html: { class: "form-control"}
	= f.input :carbohydrates, input_html: { class: "form-control"}
	= f.input :levels, input_html: { class: "form-control"}
	= f.input :extra, input_html: { class: "form-control"}
	%br/
	= f.button :submit

app/views/foodlogs/_form.html.haml
= simple_form_for(@foodlog, html:{class: 'form-horizontal'}) do |f|
	= f.input :date, label: "Date"
	= f.input :mealtype, label: "What meal is this?", input_html: {class: "form-control"}
	= f.input :meal, label: "Describe your meal", input_html: {class: "form-control"}
	= f.input :mood, label: "How are you feeling?", input_html: {class: "form-control"}
	= f.input :level, label: "What are your glucose levels?", input_html: {class: "form-control"}
	%br
	= f.button :submit 

app/views/foodlogs/edit.html.haml
%h1 Edit Food Log

= render 'form'

= link_to "Cancel", root_path

app/views/foodlogs/index.html.haml
#index_foodlogs
	- @foodlogs.each do |foodlog|
		%h2= link_to foodlog.date.strftime("%A %d %B - %H:%M %p"), foodlog
		%h3
			%span Meal Type:
			= foodlog.mealtype

app/views/foodlogs/new.html.haml
%h1 New Food Log

= render 'form'

= link_to "Cancel", root_path

app/views/foodlogs/show.html.haml
#foodlog
	%p= @foodlog.date
	%p= @foodlog.mealtype
	%p= @foodlog.meal
	%p= @foodlog.mood
	%p= @foodlog.level

#details
	%h2 Details
	= render @foodlog.details
	%h3 Add more details about your meal
	=render "details/form"


	= link_to "Back", root_path 
	|
	= link_to "Edit", edit_foodlog_path(@foodlog)
	|
	= link_to "Delete", foodlog_path(@foodlog), method: :delete, data: {confirm: "Are you sure you want to delete this?"}

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Diabetes Helper System
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
	= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
	= csrf_meta_tags

%body
	%p.notice= notice
	%p.alert= alert
	%nav.navbar.navbar-default
		.container
			.navbar-header
				= link_to "Food Log", root_path, class: "navbar-brand"
			.nav.navbar-nav.navbar-right
				= link_to "New Food Log", new_foodlog_path, class: "nav navbar-link"
	.container

		= yield